INSERT INTO ENT_USUARIO(NOME, LOGIN, SENHA, EMAIL) VALUES ('Lucas','lucas','1234','LucasTeste@gmail.com');

INSERT INTO ENT_PERFIL(DESCRICAO) VALUES('Administrador');
INSERT INTO ENT_PERFIL(DESCRICAO) VALUES('Gerente');
INSERT INTO ENT_PERFIL(DESCRICAO) VALUES('Cliente');

INSERT INTO ENT_RECURSO(NOME, CHAVE)VALUES('Tela Usuário','usuario');
INSERT INTO ENT_RECURSO(NOME, CHAVE)VALUES('Tela Perfil','perfil');
INSERT INTO ENT_RECURSO(NOME, CHAVE)VALUES('Tela Recurso','recurso');